# Generated by Django 5.0.7 on 2024-07-31 11:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("core", "0002_alter_notification_options_alter_notification_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="card_type",
            field=models.CharField(
                choices=[("master", "Master"), ("visa", "Visa"), ("verve", "Verve")],
                default="master",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="number",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="notification",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Transfer", "Transfer"),
                    ("Credit Alert", "Credit Alert"),
                    ("Debit Alert", "Debit Alert"),
                    ("Sent Payment Request", "Sent Payment Request"),
                    ("Recieved Payment Request", "Recieved Payment Request"),
                    ("Funded Credit Card", "Funded Credit Card"),
                    ("Withdrew Credit Card Funds", "Withdrew Credit Card Funds"),
                    ("Deleted Credit Card", "Deleted Credit Card"),
                    ("Added Credit Card", "Added Credit Card"),
                ],
                default="None",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reciever",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reciever_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_transactions",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_transactions",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("request_sent", "Request Sent"),
                    ("request_settled", "Request Settled"),
                    ("request_processing", "Request Processing"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("recieved", "Recieved"),
                    ("withdraw", "Withdraw"),
                    ("refund", "Refund"),
                    ("request", "Payment Request"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user"], name="core_transa_user_id_c94326_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="core_transa_date_2d33ba_idx"),
        ),
    ]
